name: Java CI

on:
    push:
        branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Rodar testes
        run: mvn test