name: Java CI

on:
    push:
        branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache do Maven
        uses: actions/cache@v4
        with:
          path: ˜/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Rodar testes
        run: mvn test